### ISSUE TITLE
Cannot use Rake at All

### ISSUE THREAD

**Issue by rizary** [sous-chefs/ruby_rbenv#102]
Hi, I am Ubuntu 14.04 user who just install ruby on rails along with mysql, etc.

I am confusing on creating db using rake db:create, or bundle exec bin/rake db:create and also rails:update:bin when i tried to fix "rails server" command

```
id@user:~/folder bundle exec bin/rake rails:update:bin/home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/history.rb:1:in `require': cannot load such file -- readline (LoadError)
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/history.rb:1:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/interface.rb:1:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/interface.rb:1:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/core.rb:5:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/core.rb:5:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug.rb:1:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug.rb:1:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
    from /home/user/AlleaProject/config/application.rb:7:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/user/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

I hope someone can enlightened me on what is going on... 

nb: I already install apache2 too...

regards,
AR

**Comment by GuanglinDu** [comment]
Take a look at this https://github.com/sstephenson/ruby-build/issues/526
