### ISSUE TITLE
rbenv: cannot change working directory to `/root'

### ISSUE THREAD

**Issue by hedgehog** [sous-chefs/ruby_rbenv#13]
Using `include_recipe 'rbenv::user'` triggers the error below.  seems to be related to this [issue](http://stackoverflow.com/questions/9951043/rbenv-permission-denied)

```
Generated at 2012-06-04 13:27:02 +1000
Chef::Exceptions::ShellCommandFailed: bash[Initialize rbenv (hedge)] (rbenv::user_install line 80) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20120604-17817-11mtszz" ----
STDOUT: export PATH="/home/hedge/.rbenv/shims:${PATH}"
source "/home/hedge/.rbenv/libexec/../completions/rbenv.bash"
rbenv rehash 2>/dev/null
STDERR: rbenv: cannot change working directory to `/root'
---- End output of "bash"  "/tmp/chef-script20120604-17817-11mtszz" ----
Ran "bash"  "/tmp/chef-script20120604-17817-11mtszz" returned 1
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:206:in `invalid!'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:192:in `error!'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/provider/execute.rb:58:in `action_run'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/provider/script.rb:33:in `action_run'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource.rb:440:in `run_action'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:45:in `run_action'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `each'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block in converge'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:76:in `converge'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:312:in `converge'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:160:in `run'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:192:in `block in run_application'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `loop'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `run_application'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application.rb:67:in `run'
/root/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-0.10.8/bin/chef-solo:25:in `<top (required)>'
/root/.rbenv/versions/1.9.2-p290/bin/chef-solo:19:in `load'
/root/.rbenv/versions/1.9.2-p290/bin/chef-solo:19:in `<main>'
```

**Comment by axsuul** [comment]
Ever figure this one out?

**Comment by hedgehog** [comment]
@axsuul, not yet.
I think the solution lies in the discussion of this issue:

http://tickets.opscode.com/browse/CHEF-2288

**Comment by axsuul** [comment]
I actually got around this issue, sorry I never came back to update this. See this commit in my fork https://github.com/axsuul/chef-rbenv/commit/f5b14775da8e4dd8bd94d100e88ab59b88ff97e0

It has to do with modifying `sudoers`. It's not the cleanest solution but at least it works.

**Comment by axsuul** [comment]
Oops! I totally referred to the wrong commit. Sorry it's been awhile. I believe this is the correct commit: https://github.com/axsuul/chef-rbenv/commit/c0c42fedbff927a74131be555917027bf0d7b039

Were you running into this issue when installing for multiple users?

**Comment by justsee** [comment]
I experienced this issue when doing app deploys with Chef. If I ran Chef as root from `/root`, then it would fail with:

```
STDERR: rbenv: cannot change working directory to `/root'
```

I have an execute resource which runs as a non-root user,  and it failed when running `rbenv exec bundle exec ...`. Setting the environment PWD, and doing cwd in the Chef execute resource did not resolve the issue.

Running `chef-client` from an accessible directory to the target user obviously avoided the issue, but wasn't sensible.

If you look at the [rbenv source line](https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv#L44) where the error is generated, you'll see that `RBENV_DIR` is the variable responsible. Setting that to an appropriate directory resolves this issue, as otherwise rbenv will set it to pwd, which returns /root. For instance

``` ruby
execute "rbenv exec bundle install --path=/vendor/bundle --deployment --without #{common_groups} --binstubs" do
  cwd new_resource.release_path
  user new_resource.owner
  environment new_resource.environment.update({
    "RBENV_DIR" => new_resource.release_path
  })
end
```

**Comment by stevenharman** [comment]
@axsuul Did you have any plans to push those changes back upstream?

**Comment by CloCkWeRX** [comment]
Yeah, pull requests welcome !

**Comment by axsuul** [comment]
I'm now using this fork: https://github.com/muskox/chef-rbenv due to this issue: https://github.com/chef-rbenv/chef-rbenv/issues/98

**Comment by CloCkWeRX** [comment]
#98 is fixed here also
