### ISSUE TITLE
ruby_rbenv::user_install error on OS X - Homebrew doesn't support multipackage

### ISSUE THREAD

**Issue by jramnani** [sous-chefs/ruby_rbenv#139]
I get the following error when using the `ruby_rbenv::user_install` recipe on my system.

```
Recipe: ruby_rbenv::user_install
  * homebrew_package[git] action install

    ================================================================================
    Error executing action `install` on resource 'homebrew_package[git]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of Chef::Node::ImmutableArray into String

    Cookbook Trace:
    ---------------
    /Users/jramnani/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:97:in `get_version_from_formula'
    /Users/jramnani/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
    /Users/jramnani/.chef/local-mode-cache/cache/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /Users/jramnani/.chef/local-mode-cache/cache/cookbooks/ruby_rbenv/libraries/chef_rbenv_recipe_helpers.rb

     42:         package node['rbenv']['install_pkgs']
     43:       end

    Compiled Resource:
    ------------------
    # Declared in /Users/jramnani/.chef/local-mode-cache/cache/cookbooks/ruby_rbenv/libraries/chef_rbenv_recipe_helpers.rb:42:in `install_rbenv_pkg_prereqs'

    homebrew_package("git") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name ["git"]
      declared_type :package
      cookbook_name "ruby_rbenv"
      recipe_name "user_install"
    end

```

I believe this is because the Homebrew package provider doesn't support multi-package.  Changing package installation to use a loop instead fixes this problem on my system.

Multi-package commit: 5ceb353e1367c2d46ac1dfa634514dae2e649e33

---

Platform: Mac OS X
Version: 10.11.2
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

**Comment by tas50** [comment]
Multipackage has been removed
