### ISSUE TITLE
selinux_state resource no longer works in chef 13

### ISSUE THREAD

**Issue by ppi2pass** [sous-chefs/ruby_rbenv#159]
Hey,
When I run this cookbook on chef 12.19.36 i'm getting the following error:
```
       Deprecated features used!
         Property `state` of resource `selinux_state` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
           - /tmp/kitchen/cache/cookbooks/selinux/resources/state.rb:22:in `class_from_file'
          See https://docs.chef.io/deprecations_property_name_collision.html for further details.
         Cloning resource attributes for firewalld_service[ssh] from prior resource
       Previous firewalld_service[ssh]: /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:57:in `from_file'
       Current  firewalld_service[ssh]: /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:61:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:61:in `from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for firewalld_rich_rule[zabbix_add] from prior resource
       Previous firewalld_rich_rule[zabbix_add]: /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:69:in `block in from_file'
       Current  firewalld_rich_rule[zabbix_add]: /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:69:in `block in from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/magento/recipes/firewalld.rb:69:in `block in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for execute[extract media] from prior resource
       Previous execute[extract media]: /tmp/kitchen/cache/cookbooks/magento/recipes/magento.rb:21:in `from_file'
       Current  execute[extract media]: /tmp/kitchen/cache/cookbooks/magento/recipes/magento.rb:31:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/magento/recipes/magento.rb:31:in `from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for yum_package[zabbix-agent] from prior resource
       Previous yum_package[zabbix-agent]: /tmp/kitchen/cache/cookbooks/magento/recipes/zabbix.rb:10:in `from_file'
       Current  yum_package[zabbix-agent]: /tmp/kitchen/cache/cookbooks/magento/recipes/scripts.rb:6:in `block in from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/magento/recipes/scripts.rb:6:in `block in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```
i've tried this in chef 13 and got the following error:
```
================================================================================
           Error executing action `permissive` on resource 'selinux_state[SELinux Permissive]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Chef::Resource::SelinuxState

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/selinux/providers/state.rb:57:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/magento/recipes/selinux.rb

             3: selinux_state "SELinux Permissive" do
             4:   action :permissive
             5: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/magento/recipes/selinux.rb:3:in `from_file'

           selinux_state("SELinux Permissive") do
             action [:permissive]
             default_guard_interpreter :default
             declared_type :selinux_state
             cookbook_name "magento"
             recipe_name "selinux"
           end

           System Info:
           ------------
           chef_version=13.0.113
           platform=centos
           platform_version=7.3.1611
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-solo worker: ppid=4465;start=22:31:20;
           executable=/opt/chef/bin/chef-solo
```
It looks like the resource needs to be renamed. i'll try to get a p/r in but might not be able to this week. anyone able to?

**Comment by szymonpk** [comment]
I don't think it's related to rbenv cookbook.

**Comment by tas50** [comment]
This isn't actually an rbenv cookbook bug. You'll need to file it against that cookbook so they can resolve it.

**Comment by ppi2pass** [comment]
sorry i must have gotten turned around when posting the issue
