### ISSUE TITLE
Unable to find 'gem' binary in path

### ISSUE THREAD

**Issue by RtypeStudios** [sous-chefs/ruby_rbenv#162]
### Cookbook version
Latest I believe, not 100% sure how to check.

### Chef-client version
13.0.118

### Platform Details
Vagrant  1.9.3, Windows 10, Hyper V

### Scenario:
Trying to run Vagrant Up

### Steps to Reproduce:
Running this vagrant file:
```
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Set the provider order.
  config.vm.provider "hyperv"
  config.vm.provider "virtualbox"

  # Choose Box
  config.vm.box = "remyjette/wily64"
  config.vm.boot_timeout = 2000
  config.vm.network :private_network, ip: "192.168.2.45"
  
  # Configure ports.
  config.vm.network :forwarded_port, guest: 5000, host: 5000 # Rails Web Server
  config.vm.network :forwarded_port, guest: 5432, host: 5432 # Postgres

  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ["mfsymlinks"]

  # Setup box details.
  config.vm.provider :hyperv do |hv|
    hv.memory = 2048
    hv.cpus = 2
  end

  # Run chef to configure software.
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]

    # Ruby
    chef.add_recipe "ruby_build"
    chef.add_recipe "ruby_rbenv::user"
   
    # Install Ruby 2.3.3 and Bundler
    chef.json = {
    
      # Configure Ruby.
      rbenv: {
        user_installs: [{
          user: 'vagrant',
          rubies: ["2.3.3"],
          global: "2.3.3",
          gems: {
            '2.3.3' => [
              { name: 'bundler'},
              { name: 'rails' },
              { name: 'rake' },
              { name: 'taps' },
              { name: 'puma' },
            ],
          }
        }]
          
      },

    }
  end
end
```

### Expected Result:
Installation of ruby 2.3.3

### Actual Result:
System errors with:
```

==> default: - change owner from '' to 'vagrant'
==> default:   * bash[Initialize rbenv (vagrant)] action run
==> default:
==> default:     [execute]
==> default: export PATH="/home/vagrant/.rbenv/shims:${PATH}"
==> default:               source "/home/vagrant/.rbenv/libexec/../completions/rbenv.bash"
==> default:               rbenv rehash 2>/dev/null
==> default:               rbenv() {
==> default:                 typeset command
==> default:                 command="$1"
==> default:                 if [ "$#" -gt 0 ]; then
==> default:                   shift
==> default:                 fi
==> default:
==> default:                 case "$command" in
==> default:                 rehash|shell)
==> default:                   eval `rbenv "sh-$command" "$@"`;;
==> default:                 *)
==> default:                   command rbenv "$command" "$@";;
==> default:                 esac
==> default:               }
==> default: [2017-05-04T04:08:36-04:00] INFO: bash[Initialize rbenv (vagrant)] ran successfully
==> default:     - execute "bash"  "/tmp/chef-script20170504-3292-4pz37q"
==> default:   * log[rbenv-post-init-vagrant] action write
==> default: [2017-05-04T04:08:36-04:00] INFO: rbenv-post-init-vagrant
==> default:
==> default:   * ruby_block[Add rbenv to PATH] action run
==> default: [2017-05-04T04:08:36-04:00] INFO: ruby_block[Add rbenv to PATH] called
==> default:
==> default:     - execute the ruby block Add rbenv to PATH
==> default: Recipe: ruby_rbenv::user
==> default:   * ruby_rbenv_ruby[2.3.3 (vagrant)] (vagrant) action install
==> default:
==> default:     * apt_package[autoconf] action install
==> default: [2017-05-04T04:08:45-04:00] INFO: apt_package[autoconf] installed autoconf at 2.69-8
==> default:       - install version 2.69-8 of package autoconf
==> default:     * apt_package[bison] action install
==> default: [2017-05-04T04:08:51-04:00] INFO: apt_package[bison] installed bison at 2:3.0.2.dfsg-2
==> default:
==> default:       - install version 2:3.0.2.dfsg-2 of package bison
==> default:     * apt_package[build-essential] action install
==> default: [2017-05-04T04:11:23-04:00] INFO: apt_package[build-essential] installed build-essential at 12.1ubuntu2
==> default:
==> default:       - install version 12.1ubuntu2 of package build-essential
==> default:     * apt_package[libssl-dev] action install
==> default: [2017-05-04T04:11:44-04:00] INFO: apt_package[libssl-dev] installed libssl-dev at 1.0.2d-0ubuntu1.5
==> default:
==> default:       - install version 1.0.2d-0ubuntu1.5 of package libssl-dev
==> default:     * apt_package[libyaml-dev] action install
==> default: [2017-05-04T04:11:49-04:00] INFO: apt_package[libyaml-dev] installed libyaml-dev at 0.1.6-3
==> default:
==> default:       - install version 0.1.6-3 of package libyaml-dev
==> default:     * apt_package[libreadline6-dev] action install
==> default: [2017-05-04T04:11:53-04:00] INFO: apt_package[libreadline6-dev] installed libreadline6-dev at 6.3-8ubuntu1
==> default:       - install version 6.3-8ubuntu1 of package libreadline6-dev
==> default:     * apt_package[zlib1g-dev] action install
==> default:  (up to date)
==> default:     * apt_package[libsqlite3-dev] action install
==> default: [2017-05-04T04:11:57-04:00] INFO: apt_package[libsqlite3-dev] installed libsqlite3-dev at 3.8.11.1-1
==> default:
==> default:       - install version 3.8.11.1-1 of package libsqlite3-dev
==> default:     * apt_package[libxml2-dev] action install
==> default: [2017-05-04T04:12:28-04:00] INFO: apt_package[libxml2-dev] installed libxml2-dev at 2.9.2+zdfsg1-4ubuntu0.4
==> default:
==> default:
==> default: - install version 2.9.2+zdfsg1-4ubuntu0.4 of package libxml2-dev
==> default:     * apt_package[libxslt1-dev] action install
==> default: [2017-05-04T04:12:34-04:00] INFO: apt_package[libxslt1-dev] installed libxslt1-dev at 1.1.28-2build2
==> default:
==> default:       - install version 1.1.28-2build2 of package libxslt1-dev
==> default:     * apt_package[libc6-dev] action install
==> default:  (up to date)
==> default:     * apt_package[libffi-dev] action install
==> default: [2017-05-04T04:12:38-04:00] INFO: apt_package[libffi-dev] installed libffi-dev at 3.2.1-3
==> default:
==> default:       - install version 3.2.1-3 of package libffi-dev
==> default:     * apt_package[libgdbm3] action install
==> default:  (up to date)
==> default:     * apt_package[libgdbm-dev] action install
==> default: [2017-05-04T04:12:41-04:00] INFO: apt_package[libgdbm-dev] installed libgdbm-dev at 1.8.3-13.1
==> default:       - install version 1.8.3-13.1 of package libgdbm-dev
==> default: [2017-05-04T04:12:41-04:00] INFO: Building ruby_rbenv_ruby[2.3.3 (vagrant)] (vagrant), this could take a while...
==> default:     * ruby_rbenv_script[rbenv install 2.3.3  (vagrant)] action run
==> default:
==> default: * script[rbenv install 2.3.3  (vagrant)] action run
==> default:
==> default:         [execute] Downloading ruby-2.3.3.tar.bz2...
==> default:                   -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.bz2
==> default:                   Installing ruby-2.3.3...
==> default:                   Installed ruby-2.3.3 to /home/vagrant/.rbenv/versions/2.3.3
==> default:
==> default: [2017-05-04T04:17:50-04:00] INFO: script[rbenv install 2.3.3  (vagrant)] ran successfully
==> default:         - execute "bash"  "/tmp/chef-script20170504-3292-guw8rd"
==> default:
==> default:     * apt_package[autoconf] action nothing (skipped due to action :nothing)
==> default:     * apt_package[bison] action nothing (skipped due to action :nothing)
==> default:     * apt_package[build-essential] action nothing
==> default:  (skipped due to action :nothing)
==> default:     * apt_package[libssl-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libyaml-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libreadline6-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[zlib1g-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libsqlite3-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libxml2-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libxslt1-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libc6-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libffi-dev] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libgdbm3] action nothing (skipped due to action :nothing)
==> default:     * apt_package[libgdbm-dev] action nothing (skipped due to action :nothing)
==> default:     * ruby_rbenv_script[rbenv install 2.3.3  (vagrant)] action nothing (skipped due to action :nothing)
==> default:
==> default:   * ruby_rbenv_global[2.3.3 (vagrant)] (vagrant) action create[2017-05-04T04:17:50-04:00] WARN: only_if block for ruby_rbenv_global[2.3.3 (vagrant)] (vagrant) returned "2.3.3", did you mean to run a command? If so use 'only_if "2.3.3"' in your code.
==> default:
==> default:     * ruby_rbenv_script[rbenv global 2.3.3 (vagrant)] action run
==> default:       * script[rbenv global 2.3.3 (vagrant)] action run
==> default: [2017-05-04T04:17:50-04:00] INFO: script[rbenv global 2.3.3 (vagrant)] ran successfully
==> default:
==> default:         - execute "bash"  "/tmp/chef-script20170504-3292-nu4jh"
==> default:
==> default:
==> default:   * [2.3.3::bundler (vagrant)] (vagrant) action install
==> default:
==> default:     ================================================================================
==> default:     Error executing action `install` on resource '[2.3.3::bundler (vagrant)] (vagrant)'
==> default:     ================================================================================
==> default:
==> default:     Chef::Exceptions::FileNotFound
==> default:     ------------------------------
==> default:     Unable to find 'gem' binary in path: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/ruby_rbenv/libraries/chef_provider_package_rbenvrubygems.rb:57:in `initialize'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/ruby_rbenv/recipes/user.rb
==> default:
==> default:      69:       rbenv_gem "#{gem['name']} (#{rbenv_user['user']})" do
==> default:      70:         package_name gem['name']
==> default:      71:         user rbenv_user['user']
==> default:      72:         root_path rbenv_user['root_path'] if rbenv_user['root_path']
==> default:      73:         rbenv_version rubie
==> default:      74:
==> default:      75:         %w(version action options source).each do |attr|
==> default:      76:           send(attr, gem[attr]) if gem[attr]
==> default:      77:         end
==> default:      78:       end
==> default:      79:     end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/ruby_rbenv/recipes/user.rb:69:in `block (3 levels) in from_file'
==> default:
==> default:     ruby_rbenv_gem("bundler (vagrant)") do
==> default:       provider Chef::Provider::Package::RbenvRubygems
==> default:       action [:install]
==> default:       default_guard_interpreter :default
==> default:       declared_type :rbenv_gem
==> default:       cookbook_name "ruby_rbenv"
==> default:       recipe_name "user"
==> default:       package_name "bundler"
==> default:       user "vagrant"
==> default:       rbenv_version "2.3.3"
==> default:     end
==> default:
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.0.118
==> default:     platform=ubuntu
==> default:     platform_version=15.10
==> default:     ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=3286;start=04:08:13;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:
==> default: [2017-05-04T04:17:50-04:00] INFO: Running queued delayed notifications before re-raising exception
==> default: Running handlers:
==> default: [2017-05-04T04:17:50-04:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-05-04T04:17:50-04:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 26 resources updated in 09 minutes 37 seconds
==> default: [2017-05-04T04:17:50-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-05-04T04:17:50-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-05-04T04:17:50-04:00] ERROR: [2.3.3::bundler (vagrant)] (vagrant) (ruby_rbenv::user line 69) had an error: Chef::Exceptions::FileNotFound: Unable to find 'gem' binary in path: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
==> default: [2017-05-04T04:17:50-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Stack out:
```
Generated at 2017-05-04 04:17:50 -0400
Chef::Exceptions::FileNotFound: [2.3.3::bundler (vagrant)] (vagrant) (ruby_rbenv::user line 69) had an error: Chef::Exceptions::FileNotFound: Unable to find 'gem' binary in path: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/provider/package/rubygems.rb:416:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/provider/package/rubygems.rb:387:in `initialize'
/var/chef/cache/cookbooks/ruby_rbenv/libraries/chef_provider_package_rbenvrubygems.rb:57:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:1399:in `new'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:1399:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:715:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:710:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:710:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:749:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/solo.rb:225:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:58:in `load'
/usr/bin/chef-solo:58:in `<main>'

>>>> Caused by Chef::Exceptions::FileNotFound: Unable to find 'gem' binary in path: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/provider/package/rubygems.rb:416:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/provider/package/rubygems.rb:387:in `initialize'
/var/chef/cache/cookbooks/ruby_rbenv/libraries/chef_provider_package_rbenvrubygems.rb:57:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:1399:in `new'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:1399:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:715:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:710:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:710:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:749:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/solo.rb:225:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:58:in `load'
/usr/bin/chef-solo:58:in `<main>'

```

**Comment by RtypeStudios** [comment]
I can see ruby is installed:

vagrant@vagrant:~$ find -name "gem"
./.rbenv/shims/gem
./.rbenv/versions/2.4.1/bin/gem

So it appears the install can find the user ruby install?

**Comment by RtypeStudios** [comment]
I've tracked this down to the new version of chef, this plugin seems to have issues with version 13+

I switch to the old version of the chef installed on the virtual by installing the omnibus plugin:

`vagrant plugin install vagrant-omnibus`

Then adding this to my chef file: 

`config.omnibus.chef_version = '12.14.60'`

I'm not sure what version the bug manifests exactly but it also affects the redisio recipe

**Comment by francocatena** [comment]
I am affected by the same error, going back to chef client 12 fixed the issue for me too.

**Comment by pndurette** [comment]
Ran into the same issue.
My temporary workaround was to wrap a `gem install` command inside the `rbenv_script` resource. Not that elegant, but works.

Considering `gem = {'name' => 'a_gem', 'version' => 'a_version' }`

```ruby
gem_install_cmd = "gem install #{gem['name']}"
gem_install_cmd += " -v #{gem['version']}" if gem['version']
gem_install_env = {'PATH' => ENV['PATH'] }
rbenv_script "install_#{gem['name']}" do
  cwd         app_dir
  user        app_user
  group       app_group
  environment gem_install_env
  code        gem_install_cmd
end
```
(Note: I reset the path because  Chef adds `/opt/chef/embedded/bin` to the path, which broke the building of some native Gem extensions, in my case)

**Comment by damacus** [comment]
We should add a Windows test suite for this error. Right now we don't have any appveyor testing. 
I'll add an issue to cover for this.

You should be able to drive Vagrant directly with test kitchen, rather than having to figure out how to code that rather large Vagrantfile yourself.

**Comment by damacus** [comment]
Hi @RtypeStudios !

We've released a new version of this cookbook, could you check that the new version closes off your bug?

I'll be closing this issue in a weeks time. Happy bug hunting

Thanks!
Dan
