### ISSUE TITLE
cannot install ruby for user

### ISSUE THREAD

**Issue by jcputter** [sous-chefs/ruby_rbenv#174]
### Cookbook version
2.0.0

### Chef-client version
Chef: 12.17.44

### Platform Details
Ubuntu 16.04.2 LTS

### Scenario:
Install ruby version for user

### Steps to Reproduce:
```
rbenv_ruby '2.3.1' do
  user 'rails'
end
```
### Expected Result:
install ruby 2.3.1

### Actual Result:
```* ruby_rbenv_ruby[2.3.1] action install
    * ruby_rbenv_plugin[ruby-build] action install

      ================================================================================
      Error executing action `install` on resource 'ruby_rbenv_plugin[ruby-build]'
      ================================================================================

      TypeError
      ---------
      no implicit conversion of nil into String

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:32:in `join'
      /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:32:in `block (2 levels) in class_from_file'
      /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:31:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/ruby_rbenv/resources/ruby.rb

       36:   rbenv_plugin 'ruby-build' do
       37:     git_url 'https://github.com/rbenv/ruby-build.git'
       38:   end
       39:

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/ruby_rbenv/resources/ruby.rb:36:in `block in class_from_file'

      ruby_rbenv_plugin("ruby-build") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :rbenv_plugin
        cookbook_name "rails_app"
        git_url "https://github.com/rbenv/ruby-build.git"
      end

      Platform:
      ---------
      x86_64-linux


    ================================================================================
    Error executing action `install` on resource 'ruby_rbenv_ruby[2.3.1]'
    ================================================================================

    TypeError
    ---------
    ruby_rbenv_plugin[ruby-build] (/var/chef/cache/cookbooks/ruby_rbenv/resources/ruby.rb line 36) had an error: TypeError: no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:32:in `join'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:32:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/plugin.rb:31:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rails_app/recipes/default.rb

     29: rbenv_ruby '2.3.1' do
     30:   user 'rails'
     31: end
     32:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rails_app/recipes/default.rb:29:in `from_file'

    ruby_rbenv_ruby("2.3.1") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rbenv_ruby
      cookbook_name "rails_app"
      recipe_name "default"
      user "rails"
      version "2.3.1"
      rbenv_action "install"
    end

    Platform:
    ---------
    x86_64-linux
```

**Comment by damacus** [comment]
@jcputter v2.0.1 has now been published. Can you check this resolves your issue please? 


I'm going to merge your issues down to this one for easier tracking/conversation.

**Comment by jcputter** [comment]
Thanks alot! Seems to be working like a charm now.

**Comment by damacus** [comment]
Brilliant! Glad it's working for you now.
