### ISSUE TITLE
cannot set global for user

### ISSUE THREAD

**Issue by jcputter** [sous-chefs/ruby_rbenv#175]
```
rbenv_global '2.3.1' do
  'rails'
end
```

Output

```    ================================================================================
    Error executing action `create` on resource 'ruby_rbenv_global[2.3.1]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/ruby_rbenv/resources/global.rb:33:in `block in class_from_file'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/global.rb:60:in `current_global_version'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/global.rb:56:in `current_global_version_correct?'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/global.rb:41:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/ts_marketingcms/recipes/default.rb

     25: rbenv_global '2.3.1' do
     26:   'rails'
     27: end
     28:

    Compiled Resource:
    ------------------
```

**Comment by damacus** [comment]
Hi @jcputter thanks for filling the bug report. 

Whilst some of the syntax of the example command is a little off. I've taken another look at the user code and it's going to fail. 

I've opened a PR for this issue here: #176

**Comment by jcputter** [comment]
seems like the user env PATH is missing the standard stuff ```/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games```

**Comment by damacus** [comment]
Mind giving this one a go?

**Comment by jcputter** [comment]
I would not, do you have any clues where to start ?

**Comment by jcputter** [comment]
not an issue. shell issue on my side. Sorry
