### ISSUE TITLE
Can't install gem without defining rbenv_version

### ISSUE THREAD

**Issue by aried3r** [sous-chefs/ruby_rbenv#188]
### Cookbook version
2.0.4

### Chef-client version
13.4.24

### Platform Details
Ubuntu 16.04 LTS

### Scenario:
Trying to install a global Ruby version and install a gem, bundler, to it.

### Steps to Reproduce:
I install Ruby like this:
```Ruby
VERSION = '2.4.2'

# Install Rbenv Globally
rbenv_system_install 'system' do
  update_rbenv
end

rbenv_ruby VERSION

rbenv_global VERSION
```
This works as expected.
Then I try to install bundler:
```Ruby
rbenv_gem 'bundler' do
  options '--no-rdoc --no-ri'
  action :upgrade
end
```

### Expected Result:
It should install bundler to the global ruby. According to the README, if I don't specify a `rbenv_version` (actually this should be called `rbenv_ruby_version`no?).

https://github.com/sous-chefs/ruby_rbenv#gem

Defining `rbenv_version '2.4.2'` manually makes it work, but that's not what the README suggest.

### Actual Result:
It seems like the version is not correctly resolved, see `versions//bin/gem` where a version should be.

```
Recipe: ruby::gems
  * ruby_rbenv_gem[bundler] action install
    * gem_package[bundler] action install

      ================================================================================
      Error executing action `install` on resource 'gem_package[bundler]'
      ================================================================================

      Errno::ENOENT
      -------------
      No such file or directory - /usr/local/rbenv/versions//bin/gem

      Resource Declaration:
      ---------------------
      # In /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/gem.rb

       39:   gem_package new_resource.package_name do
       40:     clear_sources new_resource.clear_sources if new_resource.clear_sources
       41:     include_default_source new_resource.include_default_source if new_resource.include_default_source
       42:     gem_binary binary
       43:     options new_resource.options if new_resource.options
       44:     package_name new_resource.package_name if new_resource.package_name
       45:     source new_resource.source if new_resource.source
       46:     timeout new_resource.timeout if new_resource.timeout
       47:     version new_resource.version if new_resource.version
       48:     action :install
       49:   end
       50: end

      Compiled Resource:
      ------------------
      # Declared in /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/gem.rb:39:in `block in class_from_file'

      gem_package("bundler") do
        package_name "bundler"
        action [:install]
        default_guard_interpreter :default
        declared_type :gem_package
        cookbook_name "ruby"
        gem_binary "/usr/local/rbenv/versions//bin/gem"
        options "--no-rdoc --no-ri"
        timeout 300
      end

      System Info:
      ------------
      chef_version=13.4.24
      platform=ubuntu
      platform_version=16.04
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
      program_name=chef-solo worker: ppid=20854;start=15:13:51;
      executable=/opt/chef/bin/chef-solo


    ================================================================================
    Error executing action `install` on resource 'ruby_rbenv_gem[bundler]'
    ================================================================================

    Errno::ENOENT
    -------------
    gem_package[bundler] (/home/admin/chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/gem.rb line 39) had an error: Errno::ENOENT: No such file or directory - /usr/local/rbenv/versions//bin/gem

    Resource Declaration:
    ---------------------
    # In /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ruby/recipes/gems.rb

     10: rbenv_gem 'bundler' do
     11:   options '--no-rdoc --no-ri'
     12:   action :install
     13: end

    Compiled Resource:
    ------------------
    # Declared in /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ruby/recipes/gems.rb:10:in `from_file'

    ruby_rbenv_gem("bundler") do
      action [:install]
      default_guard_interpreter :default
      declared_type :rbenv_gem
      cookbook_name "ruby"
      recipe_name "gems"
      options "--no-rdoc --no-ri"
    end

    System Info:
    ------------
    chef_version=13.4.24
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-solo worker: ppid=20854;start=15:13:51;
    executable=/opt/chef/bin/chef-solo
```

**Comment by damacus** [comment]
Yeah this might be a documentation error here. As that's the way it's setup. 

Unless you set a global or user rbenv_version it can't interpret which version to use. So doesn't:

See here for the gem resource: https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/gem.rb#L113

If you can think of a better way to describe the install behaviour (as I'm obviously making a number of assumptions) I'd appreciate a PR to the README! 


Thanks,
Dan
