### ISSUE TITLE
can not install rbenv, user or otherwise

### ISSUE THREAD

**Issue by TemporarilyOffline** [sous-chefs/ruby_rbenv#190]
### Cookbook version
2.0.4

### Chef-client version
12.9.41

### Platform Details
Ubuntu 17.04

### Scenario:
Installing rbenv_ruby with or without extra parameters

### Steps to Reproduce:
```include_recipe 'ruby_build'
rbenv_ruby '2.3.1'
```

### Expected Result:
completed convergence

### Actual Result:
```         * ruby_rbenv_ruby[2.3.1] action install
           
           ================================================================================
           Error executing action `install` on resource 'ruby_rbenv_ruby[2.3.1]'
           ================================================================================
           
           TypeError
           ---------
           no implicit conversion of nil into String
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/ruby_rbenv/resources/ruby.rb:74:in `join'
           /tmp/kitchen/cache/cookbooks/ruby_rbenv/resources/ruby.rb:74:in `ruby_installed?'
           /tmp/kitchen/cache/cookbooks/ruby_rbenv/resources/ruby.rb:56:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/wynbi-internal-dashboard/recipes/ruby.rb
           
             4: rbenv_ruby '2.3.1'
             5: 
```

I've also tried a simple block:

```
rbenv_ruby '2.3.1' do
  user 'deploy'
end

**Comment by damacus** [comment]
Hi @TemporarilyOffline please see the examples in `https://github.com/sous-chefs/ruby_rbenv/tree/master/test/fixtures/cookbooks/test/recipes` for an example how to use the cookbook. 


Thanks! 
Dan
