### ISSUE TITLE
Can't isntall ruby on MacOS

### ISSUE THREAD

**Issue by omgapuppy** [sous-chefs/ruby_rbenv#195]
### Cookbook version
2.0.5

### Chef-client version
13.6.0

### Platform Details
MacOS 10.12.6

### Scenario:
ruby_rbenv_ruby[2.4.1] action install

### Steps to Reproduce:

Trying to install global ruby to deal with the way out of date version shipped with macos

```
ruby_version = node['xcode']['rbenv']['ruby_version']

rbenv_system_install 'system'

rbenv_ruby ruby_version do
    verbose true
end

rbenv_global ruby_version do
end
```

### Expected Result:
Ruby 2.4.1 is installed and set as global

### Actual Result:

```
Recipe: xcode::rbenv
  * ruby_rbenv_system_install[system] action install
    * homebrew_package[git] action install (up to date)
    * directory[/etc/profile.d] action create (up to date)
    * template[/etc/profile.d/rbenv.sh] action create (up to date)
    * git[/usr/local/rbenv] action sync (up to date)
    * directory[/usr/local/rbenv/plugins] action create (up to date)
    * ruby_block[Add rbenv to PATH] action nothing (skipped due to action :nothing)
    * bash[Initialize system rbenv] action nothing (skipped due to action :nothing)
     (up to date)
  * ruby_rbenv_ruby[2.4.1] action install

    ================================================================================
    Error executing action `install` on resource 'ruby_rbenv_ruby[2.4.1]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    name is required

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/ruby_rbenv/resources/ruby.rb:88:in `install_ruby_dependencies'
    /var/chef/cache/cookbooks/ruby_rbenv/resources/ruby.rb:41:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/xcode/recipes/rbenv.rb

     14: rbenv_ruby ruby_version do
     15:     verbose true
     16: end
     17:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/xcode/recipes/rbenv.rb:14:in `from_file'

    ruby_rbenv_ruby("2.4.1") do
      action [:install]
      default_guard_interpreter :default
      declared_type :rbenv_ruby
      cookbook_name "xcode"
      recipe_name "rbenv"
      verbose true
    end

    System Info:
    ------------
    chef_version=13.6.0
    platform=mac_os_x
    platform_version=10.12.6
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
    program_name=chef-client worker: ppid=52948;start=16:58:10;
    executable=/opt/chef/embedded/bin/chef-client
```

**Comment by omgapuppy** [comment]
looking at https://github.com/sous-chefs/ruby_rbenv/blob/master/libraries/package_deps.rb#L15

there doesn't seem to be any mention of `mac_os_x`

exception seems to originate from: https://github.com/chef/chef/blob/master/lib/chef/property.rb#L364

**Comment by omgapuppy** [comment]
gave up, used ruby_build cookbooks as a workaround and called gem directly
