### ISSUE TITLE
Failing to install rbenv on CentOS 9

### ISSUE THREAD

**Issue by pantras** [sous-chefs/ruby_rbenv#335]
## :ghost: Brief Description

The cookbook tries to install `gdbm-devel` which is not available on CentOS 9.

## :pancakes: Cookbook version
`ruby_rbenv (5.0.21) - latest`

## :woman_cook:  Chef-Infra Version
```
System Info:
------------
chef_version=18.5.0
platform=centos
platform_version=9
ruby=ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client
```
## :tophat: Platform details
```
Operating System: CentOS Stream 9
CPE OS Name: cpe:/o:centos:centos:9
Kernel: Linux 5.14.0-480.el9.x86_64
Architecture: x86-64
```
## Steps To Reproduce

Converge a centos-9 platform using ruby_rbenv cookbook to install Ruby.

## :police_car: Expected behavior

Successful installation

## :heavy_plus_sign: 

```
Chef::Exceptions::Package
-------------------------
dnf_package[gdbm-devel] (aspera-qa-agent::rbenv line 10) had an error: Chef::Exceptions::Package: No candidate version available for gdbm-devel

Cookbook Trace: (most recent call first)
----------------------------------------
/tmp/kitchen/cache/cookbooks/ruby_rbenv/libraries/package_deps.rb:10:in `block in install_ruby_dependencies'
/tmp/kitchen/cache/cookbooks/ruby_rbenv/libraries/package_deps.rb:9:in `each'
/tmp/kitchen/cache/cookbooks/ruby_rbenv/libraries/package_deps.rb:9:in `install_ruby_dependencies'
/tmp/kitchen/cache/cookbooks/ruby_rbenv/resources/ruby.rb:64:in `block in class_from_file'

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/aspera-qa-agent/recipes/rbenv.rb:29:in `from_file'

rbenv_ruby("3.1.3") do
  action [:install]
  updated true
  updated_by_last_action true
  default_guard_interpreter :default
  declared_type :rbenv_ruby
  cookbook_name "aspera-qa-agent"
  recipe_name "rbenv"
  ruby_build_git_url "https://github.com/rbenv/ruby-build.git"
end
```

## :heavy_plus_sign: 
The package is not part of the default repository and can be installed from CodeReady Linux Builder (CRB).
`sudo dnf --enablerepo=crb -y install gdbm-devel`.

**Comment by pantras** [comment]
A workaround is to pre-install the gdbm-devel package (and also libyaml-devel for Ruby 3.3.3) from the CRB adding the following to the platform description in the kitchen.yml file:
```
    lifecycle:
      pre_converge:
      - remote: sudo dnf --enablerepo=crb -y install gdbm-devel libyaml-devel
```
