### ISSUE TITLE
Unable to install gems

### ISSUE THREAD

**Issue by lynndylanhurley** [sous-chefs/ruby_rbenv#38]
I get the following error when I try to provision my Ubuntu vagrant box:

```
[2013-03-04T18:15:01-03:00] INFO: Processing rbenv_gem[1.9.3-p392::bundler (vagrant)] (vagrant) action install (rbenv::user line 44)

================================================================================
Error executing action `install` on resource 'rbenv_gem[1.9.3-p392::bundler (vagrant)] (vagrant)'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '127'
---- Begin output of  env gempath ----
STDOUT:
STDERR: env: gempath: No such file or directory
---- End output of  env gempath ----
Ran  env gempath returned 127

Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv-3b1c59abc1134a50b0b8844954eca9a566aaffb8/libraries/chef_rbenv_mixin.rb:30:in `shell_out!'

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/recipes/user.rb

 44:       rbenv_gem "#{gem['name']} (#{rbenv_user['user']})" do
 45:         package_name    gem['name']
 46:         user            rbenv_user['user']
 47:         root_path       rbenv_user['root_path'] if rbenv_user['root_path']
 48:         rbenv_version   rubie
 49:
 50:         %w{version action options source}.each do |attr|
 51:           send(attr, gem[attr]) if gem[attr]
 52:         end
 53:       end
 54:     end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/recipes/user.rb:44:in `from_file'

rbenv_gem("bundler (vagrant)") do
  retries 0
  recipe_name "user"
  cookbook_name :rbenv
  gem_binary "export RBENV_ROOT=\"/opt/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"1.9.3-p392\" && $RBENV_ROOT/shims/gem"
  rbenv_version "1.9.3-p392"
  action :install
  user "vagrant"
  package_name "bundler"
  retry_delay 2
  provider Chef::Provider::Package::RbenvRubygems
end

[2013-03-04T18:15:01-03:00] ERROR: Running exception handlers
[2013-03-04T18:15:01-03:00] ERROR: Exception handlers complete
[2013-03-04T18:15:01-03:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-03-04T18:15:01-03:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: rbenv_gem[1.9.3-p392::bundler (vagrant)] (vagrant) (rbenv::user line 44) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
---- Begin output of  env gempath ----
STDOUT:
STDERR: env: gempath: No such file or directory
---- End output of  env gempath ----
Ran  env gempath returned 127
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Here is the provisioning section of my Vagrantfile:

``` ruby
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "~/.berkshelf/cookbooks"
    chef.add_recipe "apt"
    chef.add_recipe 'build-essential'
    chef.add_recipe 'git'
    chef.add_recipe 'vim'
    chef.add_recipe 'tmux'
    chef.add_recipe 'nginx'
    chef.add_recipe 'postgresql'
    chef.add_recipe 'stunnel'
    chef.add_recipe 'homesick'
    chef.add_recipe 'vagrant-fixes'
    chef.add_recipe 'haproxy'

    chef.add_recipe 'ruby_build'
    chef.add_recipe 'rbenv::vagrant'
    chef.add_recipe 'rbenv::user'

    chef.json = {
      'rbenv' => {
        'user_installs' => [{
          'user' => 'vagrant',
          'rubies' => ['1.9.3-p392'],
          'global' => '1.9.3-p392',
          'gems' => {
            '1.9.3-p392' => [
              {'name' => 'bundler'},
              {'name' => 'rake'},
              {'name' => 'irb'},
              {'name' => 'pry'}
            ]
          }
        }]
      },

      'homesick_castles' => {
        'dotfiles' => {
          'name' => 'lynn',
          'source' => 'https://github.com/lynndylanhurley/lynn-dotfiles.git'
        }
      }
    }

  end
```

Is this a bug, or am I doing something wrong here?

Here is my complete Vagrantfile:
https://gist.github.com/5085788

And here is my Berksfile:
https://gist.github.com/5085791

**Comment by lynndylanhurley** [comment]
I have the same issue when trying to provision a system-wide installation. Here are the settings:

``` ruby
    chef.add_recipe 'ruby_build'
    chef.add_recipe 'rbenv::vagrant'
    chef.add_recipe 'rbenv::system'

    chef.json = {
      'rbenv' => {
        'rubies' => ['1.9.3-p392'],
        'global' => '1.9.3-p392',
        'gems' => {
          '1.9.3-p392' => [
            {'name' => 'bundler'},
            {'name' => 'rake'},
            {'name' => 'irb'},
            {'name' => 'pry'}
          ]
        }
      }
    }
```

Here is the error:

```
[2013-03-04T18:56:08-03:00] INFO: Processing rbenv_gem[1.9.3-p327::bundler] (system) action install (rbenv::system line 38)

================================================================================
Error executing action `install` on resource 'rbenv_gem[1.9.3-p327::bundler] (system)'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '127'
---- Begin output of  env gempath ----
STDOUT:
STDERR: env: gempath: No such file or directory
---- End output of  env gempath ----
Ran  env gempath returned 127

Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv-3b1c59abc1134a50b0b8844954eca9a566aaffb8/libraries/chef_rbenv_mixin.rb:30:in `shell_out!'

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/recipes/system.rb

 38:     rbenv_gem gem['name'] do
 39:       rbenv_version rubie
 40:
 41:       %w{version action options source}.each do |attr|
 42:         send(attr, gem[attr]) if gem[attr]
 43:       end
 44:     end
 45:   end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/recipes/system.rb:38:in `from_file'

rbenv_gem("bundler") do
  retries 0
  rbenv_version "1.9.3-p327"
  recipe_name "system"
  cookbook_name :rbenv
  action :install
  gem_binary "export RBENV_ROOT=\"/usr/local/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"1.9.3-p327\" && $RBENV_ROOT/shims/gem"
  package_name "bundler"
  retry_delay 2
  provider Chef::Provider::Package::RbenvRubygems
end

[2013-03-04T18:56:08-03:00] ERROR: Running exception handlers
[2013-03-04T18:56:08-03:00] ERROR: Exception handlers complete
[2013-03-04T18:56:08-03:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-03-04T18:56:08-03:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: rbenv_gem[1.9.3-p327::bundler] (system) (rbenv::system line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
---- Begin output of  env gempath ----
STDOUT:
STDERR: env: gempath: No such file or directory
---- End output of  env gempath ----
Ran  env gempath returned 127
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

I've destroyed and re-created the VM several times, each time I get the same result.

**Comment by thedada95** [comment]
I have the same issue as Well !! did you managed to get through ?

**Comment by CloCkWeRX** [comment]
https://github.com/Altoros/cf-vagrant-installer/issues/50#issuecomment-20662672 - apparently fixed?
