### ISSUE TITLE
rbenv: version `global' not installed

### ISSUE THREAD

**Issue by leehambley** [sous-chefs/ruby_rbenv#43]
I'm experiencing this issue when trying to bootstrap a machine, no special configuration:

I'm not sure if `rbenv shell global` is ever a valid command? I couldn't find a lot of Google results for that, it looks like that's an alias that `chef-rbenv` is assuming exists, but it doesn't.

I couldn't see the logic of calling `rbenv shell global` at the install phase anyway.

``` json
// /roles/base.json
{
  "name": "base",
  "chef_type": "role",
  "json_class": "Chef::Role",
  "default_attributes": {
    "rbenv": {
      "upgrade": "sync",
      "rubies": [ "1.9.3-p194", "2.0.0-p0" ],
      "gems": {
        "1.9.3-p194": [{ "name": "bundler" }],
        "2.0.0-p0": [{ "name": "bundler" }]
      },
      "global": "system"
    }
  },
  "run_list": [ "recipe[rbenv::system]", "recipe[ruby_build]" ]
}
```

``` shell
$ librarian-chef show | egrep 'rbenv|ruby'
rbenv (0.7.3)
ruby_build (0.7.2)
```

``` shell
================================================================================
Error executing action `run` on resource 'script[rbenv install 1.9.3-p194 (system)]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20130330-14443-a57wz3" ----
STDOUT:
STDERR: rbenv: version `global' not installed
rbenv: no such command `install'
---- End output of "bash"  "/tmp/chef-script20130330-14443-a57wz3" ----
Ran "bash"  "/tmp/chef-script20130330-14443-a57wz3" returned 1

Resource Declaration:
---------------------
# In /tmp/chef-solo/cookbooks/rbenv/providers/script.rb

 28:   script new_resource.name do
 29:     interpreter   "bash"
 30:     code          script_code
 31:     user          new_resource.user     if new_resource.user
 32:     creates       new_resource.creates  if new_resource.creates
 33:     cwd           new_resource.cwd      if new_resource.cwd
 34:     group         new_resource.group    if new_resource.group
 35:     path          new_resource.path     if new_resource.path
 36:     returns       new_resource.returns  if new_resource.returns
 37:     timeout       new_resource.timeout  if new_resource.timeout
 38:     umask         new_resource.umask    if new_resource.umask
 39:     environment(script_environment)
 40:   end
 41:

Compiled Resource:
------------------
# Declared in /tmp/chef-solo/cookbooks/rbenv/providers/script.rb:28:in `block in class_from_file'

script("rbenv install 1.9.3-p194 (system)") do
  action "run"
  retries 0
  retry_delay 2
  command "\"bash\"  \"/tmp/chef-script20130330-14443-a57wz3\""
  backup 5
  environment {"RBENV_ROOT"=>"/usr/local/rbenv"}
  returns [0]
  code "export RBENV_ROOT=\"/usr/local/rbenv\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\n\nrbenv shell global\n\nrbenv install 1.9.3-p194\n"
  interpreter "bash"
  cookbook_name :rbenv
end

[2013-03-30T14:50:34+01:00] ERROR: Running exception handlers
[2013-03-30T14:50:34+01:00] ERROR: Exception handlers complete
[2013-03-30T14:50:34+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-03-30T14:50:34+01:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: script[rbenv install 1.9.3-p194 (system)] (/tmp/chef-solo/cookbooks/rbenv/providers/script.rb line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20130330-14443-a57wz3" ----
STDOUT:
STDERR: rbenv: version `global' not installed
rbenv: no such command `install'
---- End output of "bash"  "/tmp/chef-script20130330-14443-a57wz3" ----
Ran "bash"  "/tmp/chef-script20130330-14443-a57wz3" returned 1
chef-solo stderr: Nothing written
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/command.rb:92:in `exit_status='
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:79:in `block (4 levels) in _execute'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:550:in `call'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:550:in `do_request'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:551:in `channel_request'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:456:in `dispatch_incoming_packets'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:213:in `preprocess'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:197:in `process'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `block in loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:101:in `block (2 levels) in _execute'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:513:in `call'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:513:in `do_open_confirmation'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:535:in `channel_open_confirmation'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:456:in `dispatch_incoming_packets'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:213:in `preprocess'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:197:in `process'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `block in loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:103:in `block in _execute'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:63:in `tap'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:63:in `_execute'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:27:in `execute'
/Users/leehambley/Projects/sshipped/chef/Capfile:94:in `block (3 levels) in <top (required)>'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:15:in `instance_exec'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/backends/netssh.rb:15:in `run'
/Users/leehambley/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/sshkit-0.0.23/lib/sshkit/runners/parallel.rb:29:in `block (2 levels) in execute'
Tasks: TOP => chef-solo:install
```

**Comment by leehambley** [comment]
For whatever it's worth, I'm leaving this issue here to say that the runlist is apparently **_order dependent**_, I can hardly believe that's expected Chef behaviour given the diversity of definition possibilities, however that said, when I switched the two runlist entries, the problem goes away, and I'm able to successfully install everything.

**Comment by RichGuk** [comment]
+1 had this issue too. Making sure ruby_build was first fixed it.

**Comment by liquid1982** [comment]
+1 – I think it's better to update the README for the moment, including a note about this.

**Comment by pfhawkins** [comment]
+1 – Ran into this issue in the most recent stable release. The commit referenced above is not in the release.

**Comment by CloCkWeRX** [comment]
Dupe of #33
