### ISSUE TITLE
Crash when passing hash to "rubies" param

### ISSUE THREAD

**Issue by rb2k** [sous-chefs/ruby_rbenv#56]
This is my config:

``` ruby
 :rbenv => {
        :user_installs => [{
          :user => 'jenkins',
          :rubies => [ "1.9.3-p429", "2.0.0-p195", "jruby-1.7.4", { 'name' => "ree-1.8.7-2012.02", 'environment' => { 'CONFIGURE_OPTS' => '--no-tcmalloc' } } ],
          :vagrant => { 'system_chef_solo' => '/opt/chef/bin/chef-solo'},
          :gems => {
            "1.9.3-p429" => [{ 'name' => 'bundler' }, { 'name' => 'rake' }],
            "2.0.0-p195" => [{ 'name' => 'bundler' } ], #2.0.0 ships with rake
            "jruby-1.7.4" => [{ 'name' => 'bundler' }, { 'name' => 'rake' }],
            "ree-1.8.7-2012.02" => [{ 'name' => 'bundler' }, { 'name' => 'rake' }],
          }
        }],
      },
```

Apparently I am allowed to pass in a hash for a ruby definition ("if rubie.is_a?(Hash)"), but it will crash in the "definition" step because that one doesn't accept a Hash

```
================================================================================
Recipe Compile Error in /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb
================================================================================


Chef::Exceptions::ValidationFailed
----------------------------------
Option definition must be a kind of String!  You passed {"name"=>"ree-1.8.7-2012.02", "environment"=>{"CONFIGURE_OPTS"=>"--no-tcmalloc"}}.


Cookbook Trace:
---------------
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:29:in `block (3 levels) in from_file'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:28:in `block (2 levels) in from_file'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:26:in `each'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:26:in `block in from_file'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:22:in `each'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:22:in `from_file'


Relevant File Content:
----------------------
/tmp/vagrant-chef-1/chef-solo-2/cookbooks/rbenv/recipes/user.rb:

 22:  Array(node['rbenv']['user_installs']).each do |rbenv_user|
 23:    rubies    = rbenv_user['rubies'] || node['rbenv']['user_rubies']
 24:    gem_hash  = rbenv_user['gems'] || node['rbenv']['user_gems']
 25:  
 26:    rubies.each do |rubie|
 27:      if rubie.is_a?(Hash)
 28:        rbenv_ruby "#{rubie} (#{rbenv_user['user']})" do
 29>>         definition  rubie
 30:          user        rbenv_user['user']
 31:          root_path   rbenv_user['root_path'] if rbenv_user['root_path']
 32:          environment rubie['environment'] if rubie['environment']
 33:        end
 34:      else
 35:        rbenv_ruby "#{rubie} (#{rbenv_user['user']})" do
 36:          definition  rubie
 37:          user        rbenv_user['user']
 38:          root_path   rbenv_user['root_path'] if rbenv_user['root_path']
```

**Comment by fnichol** [comment]
It looks like #36 should close out this issue. Thank you!
