### ISSUE TITLE
[Chef 12.0.0] undefined method rbenv_rehash for Chef::Provider::Package::RbenvRubygems

### ISSUE THREAD

**Issue by aminin** [sous-chefs/ruby_rbenv#98]
Run the following commands:

```
git clone git@github.com:aminin/rbenv-fail-chef-12.git
cd rbenv-fail-chef-12
bundle install
bundle exec librarian-chef install
vagrant up
vagrant ssh -c 'wget https://www.getchef.com/chef/install.sh'
#11.16.4 works fine
# vagrant ssh -c 'sudo bash install.sh -v 11.16.4'
vagrant ssh -c 'sudo bash install.sh -v 12.0.0'
vagrant provision
```

The above script  results in error: undefined method rbenv_rehash.

System info:
Ubuntu 14.04
Vagrant 1.6.3
VirtualBox 4.3.14r95030
ruby 1.9.3p484

**Comment by aminin** [comment]
```
anton@anton-S451LB:~/workspace/rbenv-fail-chef-12$ vagrant provision
==> default: Running provisioner: chef_solo...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2014-12-07T00:34:20+00:00] INFO: Forking chef instance to converge...
==> default: [2014-12-07T00:34:20+00:00] INFO: *** Chef 12.0.0 ***
==> default: [2014-12-07T00:34:20+00:00] INFO: Chef-client pid: 1302
==> default: [2014-12-07T00:34:26+00:00] INFO: Setting the run_list to ["recipe[build-essential]", "recipe[ruby_build]", "recipe[rbenv::vagrant]", "recipe[rbenv::user]"] from CLI options
==> default: [2014-12-07T00:34:26+00:00] INFO: Run List is [recipe[build-essential], recipe[ruby_build], recipe[rbenv::vagrant], recipe[rbenv::user]]
==> default: [2014-12-07T00:34:26+00:00] INFO: Run List expands to [build-essential, ruby_build, rbenv::vagrant, rbenv::user]
==> default: [2014-12-07T00:34:26+00:00] INFO: Starting Chef Run for vagrant.vm
==> default: [2014-12-07T00:34:26+00:00] INFO: Running start handlers
==> default: [2014-12-07T00:34:26+00:00] INFO: Start handlers complete.
==> default: [2014-12-07T00:35:35+00:00] INFO: apt_package[ncurses-dev] is a virtual package, actually acting on package[libncurses5-dev]
==> default: [2014-12-07T00:36:09+00:00] INFO: git[/var/chef/cache/ruby-build] cloning repo https://github.com/sstephenson/ruby-build.git to /var/chef/cache/ruby-build
==> default: [2014-12-07T00:36:25+00:00] INFO: git[/var/chef/cache/ruby-build] checked out branch: master onto: deploy reference: 545692836e0b5690212ad30f0edc45695b23ceaf
==> default: [2014-12-07T00:36:25+00:00] INFO: git[/var/chef/cache/ruby-build] sending run action to execute[Install ruby-build] (immediate)
==> default: [2014-12-07T00:36:25+00:00] INFO: execute[Install ruby-build] ran successfully
==> default: [2014-12-07T00:36:25+00:00] INFO: template[/etc/profile.d/rbenv.sh] created file /etc/profile.d/rbenv.sh
==> default: [2014-12-07T00:36:25+00:00] INFO: template[/etc/profile.d/rbenv.sh] updated file contents /etc/profile.d/rbenv.sh
==> default: [2014-12-07T00:36:25+00:00] INFO: template[/etc/profile.d/rbenv.sh] owner changed to 0
==> default: [2014-12-07T00:36:25+00:00] INFO: template[/etc/profile.d/rbenv.sh] mode changed to 755
==> default: [2014-12-07T00:36:31+00:00] INFO: git[/home/vagrant/.rbenv] cloning repo git://github.com/sstephenson/rbenv.git to /home/vagrant/.rbenv
==> default: [2014-12-07T00:36:38+00:00] INFO: git[/home/vagrant/.rbenv] checked out branch: v0.4.0 onto: deploy reference: 9375e99f921f428849f19efe2a2e500b3295d1a7
==> default: [2014-12-07T00:36:38+00:00] INFO: bash[Initialize rbenv (vagrant)] ran successfully
==> default: [2014-12-07T00:36:38+00:00] INFO: rbenv-post-init-vagrant
==> default: [2014-12-07T00:36:38+00:00] INFO: ruby_block[Add rbenv to PATH] called
==> default: [2014-12-07T00:36:38+00:00] WARN: Cloning resource attributes for package[build-essential] from prior resource (CHEF-3694)
==> default: [2014-12-07T00:36:38+00:00] WARN: Previous apt_package[build-essential]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/build-essential/recipes/_debian.rb:24:in `block in from_file'
==> default: [2014-12-07T00:36:38+00:00] WARN: Current  apt_package[build-essential]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/providers/ruby.rb:102:in `block in install_ruby_dependencies'
==> default: [2014-12-07T00:36:38+00:00] WARN: Cloning resource attributes for package[bison] from prior resource (CHEF-3694)
==> default: [2014-12-07T00:36:38+00:00] WARN: Previous apt_package[bison]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/build-essential/recipes/_debian.rb:23:in `block in from_file'
==> default: [2014-12-07T00:36:38+00:00] WARN: Current  apt_package[bison]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/providers/ruby.rb:102:in `block in install_ruby_dependencies'
==> default: [2014-12-07T00:37:15+00:00] WARN: Cloning resource attributes for package[autoconf] from prior resource (CHEF-3694)
==> default: [2014-12-07T00:37:15+00:00] WARN: Previous apt_package[autoconf]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/build-essential/recipes/_debian.rb:21:in `block in from_file'
==> default: [2014-12-07T00:37:15+00:00] WARN: Current  apt_package[autoconf]: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/providers/ruby.rb:102:in `block in install_ruby_dependencies'
==> default: [2014-12-07T00:37:31+00:00] INFO: Building rbenv_ruby[1.9.3-p484 (vagrant)] (vagrant), this could take a while...
==> default: [2014-12-07T00:42:22+00:00] INFO: script[rbenv install 1.9.3-p484 (vagrant)] ran successfully
==> default: [2014-12-07T00:42:22+00:00] INFO: script[rbenv global 1.9.3-p484 (vagrant)] ran successfully
==> default: 
==> default: ================================================================================
==> default: Error executing action `install` on resource 'rbenv_gem[1.9.3-p484::bundler (vagrant)] (vagrant)'
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `rbenv_rehash' for #<Chef::Provider::Package::RbenvRubygems:0x00000004328c38>
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:86:in `rehash'
==> default: 
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:67:in `install_package'
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: 
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/recipes/user.rb
==> default: 
==> default:  63:       rbenv_gem "#{gem['name']} (#{rbenv_user['user']})" do
==> default:  64:         package_name    gem['name']
==> default:  65:         user            rbenv_user['user']
==> default:  66:         root_path       rbenv_user['root_path'] if rbenv_user['root_path']
==> default:  67:         rbenv_version   rubie
==> default:  68: 
==> default:  69:         %w{version action options source}.each do |attr|
==> default:  70:           send(attr, gem[attr]) if gem[attr]
==> default:  71:         end
==> default:  72:       end
==> default:  73:     end
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rbenv/recipes/user.rb:63:in `block (3 levels) in from_file'
==> default: 
==> default: rbenv_gem("bundler (vagrant)") do
==> default:   provider Chef::Provider::Package::RbenvRubygems
==> default:   action :install
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   cookbook_name :rbenv
==> default:   recipe_name "user"
==> default:   package_name "bundler"
==> default:   user "vagrant"
==> default:   rbenv_version "1.9.3-p484"
==> default:   gem_binary "export RBENV_ROOT=\"/home/vagrant/.rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"1.9.3-p484\" && $RBENV_ROOT/shims/gem"
==> default:   version "1.7.7"
==> default: end
==> default: 
==> default: 
==> default: [2014-12-07T00:42:39+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2014-12-07T00:42:39+00:00] ERROR: Running exception handlers
==> default: [2014-12-07T00:42:39+00:00] ERROR: Exception handlers complete
==> default: [2014-12-07T00:42:39+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2014-12-07T00:42:39+00:00] ERROR: rbenv_gem[1.9.3-p484::bundler (vagrant)] (vagrant) (rbenv::user line 63) had an error: NoMethodError: undefined method `rbenv_rehash' for #<Chef::Provider::Package::RbenvRubygems:0x00000004328c38>
==> default: [2014-12-07T00:42:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
anton@anton-S451LB:~/workspace/rbenv-fail-chef-12$ 
```

**Comment by nathwill** [comment]
seeing this also. from what i gather from #chef in IRC, 'chef/dsl/recipe' was pulled out of provider base in chef 12, so you have to reference resources as sub-classes (e.g. 'Chef::Resource::MyResource') in HWRPs. (ref: https://github.com/opscode/chef/issues/2591)

**Comment by mirzali** [comment]
if you go to libraries/chef_provider_package_rbenvrubygems.rb
and change

``` ruby
def rehash
  rbenv_rehash new_resource do
    root_path rbenv_root
    user rbenv_user if rbenv_user
    action :nothing
  end.run_action(:run)
end
```

to

``` ruby
def rehash
  e = ::Chef::Resource::RbenvRehash.new(new_resource, @run_context)
  e.root_path rbenv_root
  e.user rbenv_user if rbenv_user
  e.action :nothing
  e.run_action(:run)
end
```

it will work
like in https://github.com/fnichol/chef-rvm/pull/284/files

**Comment by akurkin** [comment]
any plans on resolving this issue?

**Comment by aminin** [comment]
> any plans on resolving this issue?

@thaold, meet @fnichol IRL and ask him to merge the pull request #101.

OR just use your own fork with merged PR #101.

**Comment by muskox** [comment]
This is a hack. I just applied the @mirzali code to my forked repo, putting it here in case anyone else needs to use it. https://github.com/muskox/chef-rbenv

This helps me with a Cheffile for my vagrant to run in https://github.com/muskox/muskoxchallenge/blob/master/Cheffile

**Comment by kouno** [comment]
Happened to me too. The changes on @aminin PR fixed it, but it would be nice to see this upstream :+1:.

**Comment by SimonKaluza** [comment]
:thumbsup: Thanks @aminin, worked for me too.  Looking forward to an upstream merge as well!

**Comment by muskox** [comment]
Thank you, @aminin, for figuring this out. The @aminin PR is all I did to my repo. Hopefully we'll see this upstream :+1:.

**Comment by zhiyuanshi** [comment]
I am looking forward to this issue being resolved.

**Comment by born4new** [comment]
+1

**Comment by bonzofenix** [comment]
+1

**Comment by csouls** [comment]
:sparkles: :+1: :sparkles:

**Comment by ghost** [comment]
+1

**Comment by tnaoto** [comment]
+1

**Comment by logankoester** [comment]
+1

**Comment by kazu69** [comment]
+1

**Comment by newtonlabs** [comment]
+1

**Comment by rmoriz** [comment]
:+1:

**Comment by leifmadsen** [comment]
+1 bump :)

**Comment by radius** [comment]
plus one

**Comment by hwrdprkns** [comment]
Why... isn't this being merged?

**Comment by tas50** [comment]
+1

**Comment by allomov** [comment]
+1 !!

**Comment by bplunkert** [comment]
The basic change in #101 fixes this issue for me. However, there are a few other changes in there as well, i.e. removing Gemfile.lock from .gitignore, so I opened up #108 to help move this issue along.

**Comment by irukavina** [comment]
+1

**Comment by hwrdprkns** [comment]
+1

**Comment by hwrdprkns** [comment]
@fnichol +1

**Comment by pekhee** [comment]
@fnichol Can you please merge some of these PRs? Or let someone else handle this repo.

**Comment by adamgotterer** [comment]
+1

**Comment by axos88** [comment]
+1

**Comment by he9lin** [comment]
+1

**Comment by nathantsoi** [comment]
wow there are a lot of forks... who's is the best?

**Comment by rmoriz** [comment]
I still hope that @fnichol picks up again and/or nominates a couple of new maintainers who can clean up the situation :trollface:

**Comment by nathantsoi** [comment]
agreed, until then, this is the best I could come up with: https://github.com/corewebdesign/chef-rbenv/pull/1. someone should publish their (working) fork to the chef supermarket and add a few extra maintainers

**Comment by rmoriz** [comment]
forking won't work because:
- there is already another [rbenv cookbook](https://github.com/RiotGamesCookbooks/rbenv-cookbook) on supermarket that has a different implementation 
- LWRPs automatically inherit the cookbook name for prefixing => conflicts likely
  e.g. `rbenv_ruby` = `<cookbookname>_<resource>`
  If you fork/rename the cookbook to i.e. `rbenv9000`, the resource will be named `rbenv9000_ruby` and break all dependencies.
- Chef in general does not have a "namespace" concept like github, only a flat model like Rubygems.

You can just fork it on github and mess with your local Berksfile to use that fork (via git). :-(

**Comment by nathantsoi** [comment]
https://supermarket.chef.io/cookbooks/hostnames is a fork of https://supermarket.chef.io/cookbooks/hostname just need to do some renaming...
